# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaluser',
            name='session_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='session_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
